export { default as Welcome } from "./AdminStatic/Welcome";
export { default as StaticPage } from "./Visacare/StaticPage";
export { default as LoginPage } from "./Login/Login";
export { default as PasscodePage } from "./Login/SecretKey";
export { default as ForgotPasswordPage } from "./Login/Forgotpassword";
export { default as OtpEnterValidPage } from "./Login/OtpEnterValid";
export { default as SetPassword } from "./Login/SetNewPassword";
export { default as DynamicPage } from "./Visacare/DynamicPage";
export {default as PatientLoginDashboard} from './Patient/PatientLoginDashboard';
export {default as CreatePatientPage} from './Patient/CreatePatient';
export {default as AdmitPatientPage} from './Patient/AdmitPatient';
export {default as PatientInfoPage} from './Patient/PatientInfo';
export {default as AdminDashboardPage} from './Admin/AdminDashboard';
export {default as PatientDetailsPage} from './Patient/PatientDetails';
export { default as ViewForm } from "./Visacare/ViewForm";
export { default as AddFields } from "./Visacare/AddFields";
export { default as ViewFields } from "./Visacare/ViewFields";
export { default as CreateNewForm } from "./Visacare/CreateNewForm";
export { default as SafetyCheck } from "./Visacare/Q15SafetyCheck";
export { default as AdminScheduleChanges } from "./Visacare/AdminScheduleChanges";
export { default as AbInMoSc } from "./Forms/AIMS";
export { default as StaffInfoPage } from "./Staff/StaffInfo";
export { default as AllStaffDetailsPage } from "./Staff/AllStaffDetails";
export { default as OrganizationDetailsPage } from "./Organization/OrganizationDetails";
export { default as PatientStaffAssignmentPage } from "./Staff_Patient/PatientStaffAssignment";
export { default as BedMasterConfiguration } from "./Bed/BedMasterConfiguration";
export { default as AllPatientBedAssignListPage } from "./Bed/AllPatientBedAssignList";
export { default as AdmitPatientupdated } from "./Patient/AdmitPatientupdated";
export { default as AddOrganizationPage } from "./Organization/AddOrganization";
export { default as AllOrganizationList } from "./Organization/AllOrganizationDetails";
export { default as VisitPatientDetailsPage } from "./Patient/VisitPatientDetails";
export { default as PatientBedAssignment } from "./Bed/PatientBedAssignment";
export { default as DynamicBedAssignPage } from "./Bed/DynamicBedAssign";
export { default as BedAssignInformationPage } from "./Bed/BedAssignInformation";
export { default as PatientStaffAssignDetailsPage } from "./Staff_Patient/PatientStaffAssignDetails";
export { default as VisitPatientdata } from "./Patient/VisitPatient";
export { default as AddPatientVitals } from "./Patient/AddPatientVitals";
export { default as AddPatientProblem } from "./Patient/AddPatientProblem";
export { default as AddAllergy } from "./Patient/AddAllergy";
export { default as SkinAllergy } from "./Patient/SkinAllergy";
export { default as PatientProblem } from "./Patient/PatientProblemInfo";
export { default as AddProcedure } from "./Patient/AddProcedure";
export { default as BoneMarrowBiopsy } from "./Patient/BoneMarrowBiopsy";
export { default as AddImagingProcedure } from "./Patient/AddImagingProcedure";
export { default as PatientCtScan } from "./Patient/PatientCtScan";
export { default as AddPatientLabTest } from "./Patient/AddPatientLabTest";
export { default as AddPatientLabTestview } from "./Patient/AddPatientLabTestview";
export { default as AddPatientImmunization } from "./Patient/AddPatientImmunization";
export { default as AddImmunizationView } from "./Patient/ImmunizationView";
export { default as ViewProcedure } from "./Patient/ViewProcedure";
export { default as AAbnormalForm } from "./Forms/AAbnormalForm";
export { default as AddMultiVital } from "./Patient/AddMultiVital";
export { default as Q15Reports } from "./Patient/Q15Reports";
export { default as Q15ReportsViews } from "./Patient/Q15ReportsViews";
export { default as AddAdmission } from "./Patient/AddAdmission";
export { default as VpatientVisit } from "./Patient/VpatientVisit";
export { default as AddProcedureconsult } from "./Patient/AddProcedureconsult";
export { default as TestingStaticIndexFormPage } from "./Visacare/TestingStaticIndexForm";
export { default as TestingDynamicIndexformPage } from "./Visacare/TestingDynamicIndexform";
export { default as IndexFormController  } from "./Visacare/IndexFormController";